# Site settings
title: Seth Dorris
email: sethc.dorris@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the personal website for Nashville Software School Graduate, Seth Dorris. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "sethdorris.github.io" # the base hostname & protocol for your site
twitter_username: seth_dorris
github_username:  sethdorris

# Build settings
markdown: kramdown
